# $FreeBSD$

PORTNAME=	libyuv
PORTVERSION=	0.0.1280
CATEGORIES=	graphics
MASTER_SITES=	http://files.freeswitch.org/downloads/libs/

MAINTAINER=	amijaresp@gmail.com
COMMENT=	YUV scaling and conversion functionality

USES=		cmake
USE_LDCONFIG=	yes

.include <bsd.port.mk>
